In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [10]:
np.array(my_list)

array([1, 2, 3])

In [11]:
l=np.array(my_list)

In [12]:
l.shape

(3,)

In [4]:
matrix=[[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
n=np.array(matrix)

In [9]:
n.shape

(3, 3)

In [13]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [36]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [38]:
np.empty([2,2])

array([[ 2.5,  5. ],
       [ 7.5, 10. ]])

In [39]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.eye(4,3,1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.random.rand(3)

array([0.41928193, 0.91059985, 0.46469126])

In [46]:
np.random.rand(5,5)

array([[0.32829969, 0.70633981, 0.16295331, 0.51463068, 0.51105285],
       [0.17976619, 0.69287497, 0.68543911, 0.45398985, 0.72024585],
       [0.01971597, 0.72010706, 0.01348201, 0.49971663, 0.11829674],
       [0.00119586, 0.0070395 , 0.97293273, 0.20915603, 0.58016517],
       [0.92273109, 0.12634963, 0.28839031, 0.12653312, 0.92129135]])

In [47]:
np.random.randn(2)

array([0.50929979, 0.21700755])

In [48]:
np.random.randn(5,5)

array([[-0.27466044,  1.53620197, -1.73085968, -0.21675073, -1.19324714],
       [ 0.26291097,  1.19711564,  0.43418051,  1.16980975, -1.46863904],
       [-0.15088006, -1.32930324, -0.61967473,  1.53348662, -0.12035758],
       [ 0.39708711,  0.90268328, -0.52631583, -0.04304173,  1.23296542],
       [ 1.53536217, -0.07476206,  0.49063697,  1.24139161, -1.36096949]])

In [49]:
np.random.randint(100)

55

In [51]:
np.random.randint(5,size=(2,4))

array([[4, 4, 2, 3],
       [1, 3, 4, 1]])

In [52]:
np.random.randint(1,100,10)

array([62,  1, 64, 15, 38, 23, 36, 33, 32, 61])

In [54]:
arr=np.linspace(10,40,16)
arr

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40.])

In [61]:
newarr=arr.reshape(4,4)
newarr

array([[10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.],
       [34., 36., 38., 40.]])

In [62]:
newarr.reshape(16)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40.])

In [74]:
arr1=np.linspace(30,11,20,dtype=int)
arr1

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11])

In [75]:
newarr1=arr1.reshape(4,5)
newarr1

array([[30, 29, 28, 27, 26],
       [25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11]])

In [79]:
a=np.linspace(30,11,20,dtype=int).reshape(5,4)
a

array([[30, 29, 28, 27],
       [26, 25, 24, 23],
       [22, 21, 20, 19],
       [18, 17, 16, 15],
       [14, 13, 12, 11]])

In [80]:
a.reshape(20)

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11])

In [82]:
np.linspace(30,11,20,dtype=int).reshape(1,-1)

array([[30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
        14, 13, 12, 11]])

In [85]:
np.linspace(30,11,20,dtype=int).reshape(1,-1)

array([[30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
        14, 13, 12, 11]])

In [90]:
a=np.linspace(1,17,17)
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17.])

In [91]:
a.reshape(1,-1)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17.]])

In [93]:
ran=np.random.randint(0,100,10)
ran

array([28,  4, 51, 18, 70, 75, 13, 23, 67, 37])

In [94]:
ran.max()

75

In [95]:
ran.min()

4

In [97]:
ran.argmin()

1

In [98]:
ran.argmax()

5

In [102]:
arr=np.random.randint(20,100,36).reshape(6,6)
arr

array([[88, 32, 57, 58, 91, 37],
       [68, 81, 41, 50, 48, 63],
       [21, 35, 73, 92, 59, 51],
       [88, 34, 36, 28, 74, 39],
       [78, 55, 41, 31, 21, 72],
       [64, 54, 41, 72, 71, 21]])

In [103]:
arr[1,0]

68

In [106]:
arr[4: ,4:]

array([[21, 72],
       [71, 21]])

In [108]:
arr[4: ,0]

array([78, 64])

In [109]:
arr[1][0]

68

In [110]:
arr[:,0]

array([88, 68, 21, 88, 78, 64])

In [113]:
arr[:0:1]

array([], shape=(0, 6), dtype=int32)

In [118]:
an=np.random.randint(10,100,20)
an

array([14, 50, 35, 20, 40, 93, 81, 20, 65, 15, 97, 68, 92, 98, 96, 72, 29,
       11, 13, 53])

In [120]:
an[an>=50]

array([50, 93, 81, 65, 97, 68, 92, 98, 96, 72, 53])

In [117]:
an[an<50]

array([30, 49, 39, 38, 14, 11, 27, 42, 11])

In [123]:
matrix=[[[1,2,3],[4,5,6],[7,8,9]]]
matrix

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [ ]:
slice